### ISSUE TITLE
Nome para o app? (mesmo que provisório)

### ISSUE THREAD

**Issue by bernardoadc** [khullah/PECNjs#2]
O nome atual (PECNjs) é apenas uma abreviação para Projeto Educacional Colaborativo - grupo de NodeJs. Agora que já temos um tema definido (https://github.com/khullah/PECNjs/issues/1) podemos pensar em algo mais amigável

**Comment by KesleyDavid** [comment]
Uma sugestão seria DevNet

**Comment by llucasmota** [comment]
Para o bot: Telbot

**Comment by t7gs** [comment]
Updeveloper

**Comment by bernardoadc** [comment]
Pela votação, será **DevNet**. Boa @KesleyDavid !
